version: "3.8"
services:
  postgres_myhero:
    image: postgres:15
    container_name: postgres_myhero
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: myhero_user
      POSTGRES_PASSWORD: myhero_password
      POSTGRES_DB: myhero_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis_myhero:
    image: redis:7
    container_name: redis_myhero
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

  myhero_app:
    build: .
    container_name: myhero_app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres_myhero
      - redis_myhero

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
